services:
  dev-db:
    image: postgres:13
    container_name: signify-db
    ports:
      - "5434:5432"        
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: signify_db
    networks:
      - forward
    volumes:
      - db_data:/var/lib/postgresql/data  

networks:
  forward:

volumes:
  db_data:
